# Generated by Django 2.2.7 on 2019-12-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('mol_H', models.IntegerField(verbose_name='[H+]')),
                ('all_mol', models.IntegerField(verbose_name='Cm')),
            ],
        ),
        migrations.CreateModel(
            name='Hydroxide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('mol_OH', models.IntegerField(verbose_name='[OH-]')),
                ('all_mol', models.IntegerField(verbose_name='Cm')),
            ],
        ),
    ]
