# Generated by Django 2.2.7 on 2019-12-27 21:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acid',
            name='V',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='acid',
            name='when_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 21, 44, 47, 718225, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='hydroxide',
            name='V',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hydroxide',
            name='when_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 21, 44, 47, 734462, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr', models.PositiveIntegerField(default=1)),
                ('V', models.FloatField(default=0.0)),
                ('pH', models.PositiveSmallIntegerField(default=7)),
                ('aim_pH', models.PositiveSmallIntegerField(default=7)),
                ('CmH', models.FloatField(default=1e-07)),
                ('pHs', models.CharField(default='', max_length=255)),
                ('Vs', models.CharField(default='', max_length=255)),
                ('acids', models.ManyToManyField(default=None, to='chemistry.Acid')),
                ('hydroxides', models.ManyToManyField(default=None, to='chemistry.Hydroxide')),
            ],
        ),
    ]
