# Generated by Django 2.2.7 on 2019-12-27 21:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry', '0003_auto_20191227_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='Plot',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='acid',
            name='when_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 21, 47, 39, 590360, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hydroxide',
            name='when_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 27, 21, 47, 39, 606919, tzinfo=utc)),
        ),
    ]
